//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleKardex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleKardex()
        {
            this.MovimientoKardex = new HashSet<MovimientoKardex>();
        }
    
        public int IDDetalleKardex { get; set; }
        public int IDKardex { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Concepto { get; set; }
        public string No_Documento { get; set; }
    
        public virtual Kardex Kardex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoKardex> MovimientoKardex { get; set; }
    }
}
