//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kardex()
        {
            this.DetalleKardex = new HashSet<DetalleKardex>();
        }
    
        public int IDKardex { get; set; }
        public int CantidadMax { get; set; }
        public int CantidadMin { get; set; }
        public int IDProducto { get; set; }
        public int IDBodega { get; set; }
        public int IDMetodo { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleKardex> DetalleKardex { get; set; }
        public virtual Metodo Metodo { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
