//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolVentana
    {
        public int IDRol { get; set; }
        public int IDVentana { get; set; }
        public int IDTipoPermiso { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual TipoPermiso TipoPermiso { get; set; }
        public virtual Ventana Ventana { get; set; }
    }
}
