//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int IDDetalleFactura { get; set; }
        public string No_Factura { get; set; }
        public int IDProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal TotalItem { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
