//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoKardex
    {
        public int IDMovimientoKardex { get; set; }
        public int IDDetalleKardex { get; set; }
        public int IDTipoMovimientoKardex { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal PrecioTotal { get; set; }
    
        public virtual DetalleKardex DetalleKardex { get; set; }
        public virtual TipoMovimientoKardex TipoMovimientoKardex { get; set; }
    }
}
